/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sys/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 创建系统用户
         * @description 创建系统用户
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            data?: {
                                /** @description ID 编号 */
                                id: number;
                                /** @description 用户名 */
                                userName?: string;
                                /** @description 头像 */
                                avatar?: string;
                                /** @description 性别 */
                                gender?: string;
                                /** @description 昵称 */
                                nickName?: string;
                                /** @description 手机 */
                                phone?: string;
                                /** @description 邮箱 */
                                email?: string;
                                /** Format: date-time */
                                createTime?: string;
                                /** Format: date-time */
                                updateTime?: string;
                            };
                            message: string;
                            success: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取系统用户
         * @description 获取系统用户
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            data?: {
                                /** @description ID 编号 */
                                id: number;
                                /** @description 用户名 */
                                userName?: string;
                                /** @description 头像 */
                                avatar?: string;
                                /** @description 性别 */
                                gender?: string;
                                /** @description 昵称 */
                                nickName?: string;
                                /** @description 手机 */
                                phone?: string;
                                /** @description 邮箱 */
                                email?: string;
                                /** Format: date-time */
                                createTime?: string;
                                /** Format: date-time */
                                updateTime?: string;
                            };
                            message: string;
                            success: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * 删除某个系统用户
         * @description 删除某个系统用户
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            data?: {
                                /** @description ID 编号 */
                                id: number;
                                /** @description 用户名 */
                                userName?: string;
                                /** @description 密码 */
                                password?: string;
                                /** @description 头像 */
                                avatar?: string;
                                /** @description 性别 */
                                gender?: string;
                                /** @description 昵称 */
                                nickName?: string;
                                /** @description 手机 */
                                phone?: string;
                                /** @description 邮箱 */
                                email?: string;
                                /** Format: date-time */
                                createTime?: string;
                                /** Format: date-time */
                                updateTime?: string;
                            };
                            message: string;
                            success: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * 更新某个系统用户
         * @description 更新系统用户
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            data?: {
                                /** @description ID 编号 */
                                id: number;
                                /** @description 用户名 */
                                userName?: string;
                                /** @description 密码 */
                                password?: string;
                                /** @description 头像 */
                                avatar?: string;
                                /** @description 性别 */
                                gender?: string;
                                /** @description 昵称 */
                                nickName?: string;
                                /** @description 手机 */
                                phone?: string;
                                /** @description 邮箱 */
                                email?: string;
                                /** Format: date-time */
                                createTime?: string;
                                /** Format: date-time */
                                updateTime?: string;
                            };
                            message: string;
                            success: boolean;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/sys/user/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有系统用户
         * @description 获取系统用户
         */
        get: {
            parameters: {
                query?: {
                    /** @description 分页大小 */
                    pageSize?: string;
                    /** @description 分页页数 */
                    pageNum?: string;
                    /** @description 筛选用户名 */
                    username?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": Record<string, never>;
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: {
                                /** @description 分页大小 */
                                list: {
                                    /** @description 用户名 */
                                    userName?: string;
                                    /** @description 头像 */
                                    avatar?: string;
                                    /** @description 性别 */
                                    gender?: string;
                                    /** @description 昵称 */
                                    nickName?: string;
                                    /** @description 手机 */
                                    phone?: string;
                                    /** @description 邮箱 */
                                    email?: string;
                                    /** Format: date-time */
                                    createTime?: string;
                                    /** Format: date-time */
                                    updateTime?: string;
                                }[];
                                /** @description 分页页数 */
                                total: number;
                            };
                            message: string;
                            success: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/user/{id}/assign-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 给某个用户分配角色 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: string;
                            message: string;
                            /** @default true */
                            success: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/user/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重置某个用户密码
         * @description 重置某个用户密码
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            /** @default true */
                            success: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/user/{id}/role-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取某个用户相关的角色id
         * @description 获取某个用户相关的角色id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: number[];
                            message: string;
                            /** @default true */
                            success: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 管理台登录
         * @description 管理台登录
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: {
                                user: {
                                    /** @description ID 编号 */
                                    id: number;
                                    /** @description 用户名 */
                                    userName?: string;
                                    /** @description 头像 */
                                    avatar?: string;
                                    /** @description 性别 */
                                    gender?: string;
                                    /** @description 昵称 */
                                    nickName?: string;
                                    /** @description 手机 */
                                    phone?: string;
                                    /** @description 邮箱 */
                                    email?: string;
                                    /** Format: date-time */
                                    createTime?: string;
                                    /** Format: date-time */
                                    updateTime?: string;
                                };
                                roles: string[];
                                permissions: string[];
                            };
                            message: string;
                            /** @default true */
                            success: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/captcha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取登录验证码
         * @description 获取登录验证码
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: {
                                image: string;
                                uuid: string;
                                captcha: string;
                            };
                            message: string;
                            /** @default true */
                            success: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaginationResult: {
            /** @description 分页大小 */
            list: string[];
            /** @description 分页页数 */
            total: number;
        };
        SysUser: {
            /** @description ID 编号 */
            id: number;
            /** @description 用户名 */
            userName?: string;
            /** @description 密码 */
            password?: string;
            /** @description 头像 */
            avatar?: string;
            /** @description 性别 */
            gender?: string;
            /** @description 昵称 */
            nickName?: string;
            /** @description 手机 */
            phone?: string;
            /** @description 邮箱 */
            email?: string;
            /** Format: date-time */
            createTime?: string;
            /** Format: date-time */
            updateTime?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
